# Generated by Django 3.0.6 on 2020-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
